# Site settings
baseurl = "/"
# HTML Language Code Reference, such as en, zh-cn
copyright = "Ryan Watters, ELS"
languageCode = "en"
title = "Confab 2017"
theme = "hugo-theme-blueberry-detox"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
hasCJKLanguage = false

[params]
	name = "Ryan Watters, ELS"
	author = "Ryan Watters, ELS"
	description = "A few blog posts sharing my experience at Confab Central, 2017, in Minneapolis"
	bio = "I am a content strategist, editor, creative and technical writer, and frontend developer."
	# Enter optionally your twitter account
	twitter_name = "ryandwatters"
	github = "rdwatters"
	enableRSS = false

	# Disqus comment
	disqusShortname = ""
	# Disable disqus comments by set `enableDisqus = "false"`
	enableDisqus = false

	# Duoshuo comment
	duoshuoShortname = ""
	# Disable duoshuo comments by set `enableDuoshuo = "false"`
	enableDuoshuo = false

	enableGithubIssuesTips = false

	# Enable googleAnalytics
	enableGoogleAnalytics = false

	# Enable baiduAnalytics
	enableBaiduAnalytics = false
	# Baidu Tongji Code
	baiduAnalytics = ''

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = "/"
	about = "About"
	tags = "Tags"
	archive = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "My name is Ryan Watters."
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
  # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle = ""

[blackfriday]
  angledQuotes = false
  fractions = false
  plainIDAnchors = true
  hrefTargetBlank = true

[taxonomies]
	tags = "tag"


# Add additional social link entries underneath
[social]
  twitter-square = "ryandwatters"
  github-square = "rdwatters"
